### ISSUE TITLE
"la melbi" should be one person, so it should not be translated to "they"

### ISSUE THREAD

**Issue by VitoVan** [daeldir/jbogidva#4]
coi do.

Thanks for your work on jbogidva, it's a great tool to learn lojban.

I am reading the article "la melbi .e le ractu", then I may found something wrong in English, but I'm not sure.

first, we said: '{la melbi ku prenu|There once was **A PERSON** called Melbi.}'

https://github.com/daeldir/jbogidva/blob/00d8e925eed103275f3ddf624a2a9fd4a0067acd/en/la-melbi-e-le-ractu.html#L30

then, we said: '{zvati le zdani|**THEY** were in their house.}'

https://github.com/daeldir/jbogidva/blob/00d8e925eed103275f3ddf624a2a9fd4a0067acd/en/la-melbi-e-le-ractu.html#L32

I'm not a native English speaker, but when I read this, it's kind of wired, am I wrong?

**Comment by daeldir** [comment]
It is indeed weird. I just used the translation given by the original author. We can now find this text [here](http://foldr.moe/la-melbi-e-le-ractu/), and its translation [here](http://foldr.moe/la-melbi-e-le-ractu/glico). A problem that arise if we want to switch to the first person, however, is that we do not know the gender of Melbi. Is it a he or a she? It is not specified in the lojban source. Choosing a gender feels wrong, using “it” is frowned upon when talking about people, and going to look for other gender neutral pronouns such as “xe”, “ze”, or using “s/he” feels like opening a can of worms while this issue is not resolved in society ;-). A quick search on the subject lead me to [this Wikipedia article](https://en.wikipedia.org/wiki/Third-person_pronoun), which suggest, amongst other solution, the singular “they” that we see used here. Another solution would be “One was in its house”, but I am not sure that it would be any less weird. 

So, while I agree with you, by looking for another translation I reached the conclusion that it may be, in fact, correct. Another issue is that I do not feel comfortable modifying the translation provided by the original author, but if we find a way to improve the translation, I will contact the author to suggest the improvement “upstream”.

And thank you for the mention that it is a great tool. I’m sorry that I don’t have more time to work on it and that it is for now frozen in a state of barely useful. I won’t ignore issues such as this one, nor pull requests, but I can’t dedicate the time to add new texts, or even improve the translations structure – as can be seen in “la .teris.” where only the beginning of the text is close to what I really want. Which is a shame, because as long as I have this few texts and everything is fully translated, the didactic value is lost (we need sufficient repetition so that we can stop translating more and more words as they are becoming familiar, and engage the brain to do the job that is currently done by the mouse).

**Comment by VitoVan** [comment]
ki'e do

I learned a lot from your comment, thank you.

Don't feel sorry for your lack of time on this work, you have done a wonderful start, it is in a good state for others to contribute. Which there's no need to feel shameful at all.

I may see what I can help in the future.

At last, it feels good to have this conversation with you, thank you.
